version: '3'
volumes:
  rabbitmq_data:
      driver: local
  mongodb_data:
      driver: local
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - nodejs-order
  mongodb:
    image: docker.io/library/mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - nodejs-order
networks:
  nodejs-order:
    driver: bridge
      
